apiVersion: apps/v1
kind: Deployment
metadata:
    generation: 1
    labels:
        control-plane: controller-manager
        olm.deployment-spec-hash: 6cf8d7f8d6
        olm.owner: aap-operator.v2.4.0-0.1702352614
        olm.owner.kind: ClusterServiceVersion
        olm.owner.namespace: ansible-prod-axa-es
        operators.coreos.com/ansible-automation-platform-operator.aap: ''
    name: automation-controller-operator-controller-manager
    namespace: ansible-prod-axa-es
spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 1
    selector:
        matchLabels:
            control-plane: controller-manager
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            labels:
                control-plane: controller-manager
        spec:
            containers:
            -   args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                env:
                -   name: OPERATOR_CONDITION_NAME
                    value: aap-operator.v2.4.0-0.1702352614
                image: registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:3b0eb7d2d3ac3ab0ed847c521f2c5a629e579a8778829a71d5841e762eea5fb9
                imagePullPolicy: IfNotPresent
                name: kube-rbac-proxy
                ports:
                -   containerPort: 8443
                    name: https
                    protocol: TCP
                resources:
                    limits:
                        cpu: 500m
                        memory: 128Mi
                    requests:
                        cpu: 5m
                        memory: 64Mi
                securityContext:
                    allowPrivilegeEscalation: false
                terminationMessagePath: /dev/termination-log
                terminationMessagePolicy: File
            -   args:
                - --health-probe-bind-address=:6789
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                - --leader-election-id=automation-controller-operator
                env:
                -   name: ANSIBLE_GATHERING
                    value: explicit
                -   name: ANSIBLE_DEBUG_LOGS
                    value: 'false'
                -   name: WATCH_NAMESPACE
                    valueFrom:
                        fieldRef:
                            apiVersion: v1
                            fieldPath: metadata.annotations['olm.targetNamespaces']
                -   name: RELATED_IMAGE_CONTROLLER
                    value: registry.redhat.io/ansible-automation-platform-24/controller-rhel8@sha256:9f4908f8f9eb6bc803c0c09fb9206699073fad991b58d373c5602a664ec3bce3
                -   name: RELATED_IMAGE_CONTROLLER_INIT_CONTAINER
                    value: registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8@sha256:b6aed81bd8bf840db5e98a37a0d6fc6a2ce679c3ce5ddbf5a2f2c5c241c6c059
                -   name: RELATED_IMAGE_CONTROLLER_INIT_PROJECTS_CONTAINER
                    value: registry.redhat.io/ubi8/ubi-minimal@sha256:87bcbfedfd70e67aab3875fff103bade460aeff510033ebb36b7efa009ab6639
                -   name: RELATED_IMAGE_CONTROLLER_REDIS
                    value: registry.redhat.io/rhel8/redis-6@sha256:26573f1230a3c7df5475d5968bf6595719950906f8e7594b5394ad6fcab9b0e4
                -   name: RELATED_IMAGE_CONTROL_PLANE_EE
                    value: registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8@sha256:b6aed81bd8bf840db5e98a37a0d6fc6a2ce679c3ce5ddbf5a2f2c5c241c6c059
                -   name: RELATED_IMAGE_CONTROLLER_POSTGRES
                    value: registry.redhat.io/rhel8/postgresql-13@sha256:6ecee6d67013493b2735d7c300b0809e4c261a0f682d8f981d5cc4058e990c4c
                -   name: RELATED_IMAGE_EE_SUPPORTED
                    value: registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8@sha256:b6aed81bd8bf840db5e98a37a0d6fc6a2ce679c3ce5ddbf5a2f2c5c241c6c059
                -   name: RELATED_IMAGE_EE_MINIMAL
                    value: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8@sha256:0851fb85bf5a75831277b54c636da1854d50a5ac2a5fa2ddc1c6b768cb02ae77
                -   name: OPERATOR_CONDITION_NAME
                    value: aap-operator.v2.4.0-0.1702352614
                image: registry.redhat.io/ansible-automation-platform-24/controller-rhel8-operator@sha256:e6e057edaa8b74e888e20f2f654987f15ec69a5a0c25d13562df6ad6eb1fa683
                imagePullPolicy: IfNotPresent
                livenessProbe:
                    failureThreshold: 3
                    httpGet:
                        path: /healthz
                        port: 6789
                        scheme: HTTP
                    initialDelaySeconds: 15
                    periodSeconds: 20
                    successThreshold: 1
                    timeoutSeconds: 1
                name: automation-controller-manager
                readinessProbe:
                    failureThreshold: 3
                    httpGet:
                        path: /readyz
                        port: 6789
                        scheme: HTTP
                    initialDelaySeconds: 5
                    periodSeconds: 10
                    successThreshold: 1
                    timeoutSeconds: 1
                resources:
                    limits:
                        cpu: '2'
                        memory: 4Gi
                    requests:
                        cpu: 50m
                        memory: 32Mi
                securityContext:
                    allowPrivilegeEscalation: false
                    capabilities:
                        drop:
                        - ALL
                terminationMessagePath: /dev/termination-log
                terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            imagePullSecrets:
            -   name: redhat-operators-pull-secret
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext:
                runAsNonRoot: true
            serviceAccount: automation-controller-operator-controller-manager
            serviceAccountName: automation-controller-operator-controller-manager
            terminationGracePeriodSeconds: 10
status:
    availableReplicas: 1
    conditions:
    -   lastTransitionTime: '2024-02-09T08:35:42Z'
        lastUpdateTime: '2024-02-09T08:35:42Z'
        message: Deployment has minimum availability.
        reason: MinimumReplicasAvailable
        status: 'True'
        type: Available
    -   lastTransitionTime: '2024-02-09T08:35:01Z'
        lastUpdateTime: '2024-02-09T08:35:42Z'
        message: ReplicaSet "automation-controller-operator-controller-manager-6c8f8d589d"
            has successfully progressed.
        reason: NewReplicaSetAvailable
        status: 'True'
        type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
