apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: system:deployers
    namespace: ansible-prod-axa-es
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: system:deployer
subjects:
-   kind: ServiceAccount
    name: deployer
    namespace: ansible-prod-axa-es
